#!/bin/bash
CONTAINER_NAME=container_build_deepinwine_tim
buildah from --name ${CONTAINER_NAME} localhost/arch_sandbox_deepinwine:latest
buildah run ${CONTAINER_NAME} sudo -u builder paru --noconfirm -S com.qq.tim.spark
buildah run ${CONTAINER_NAME} rm -rf /var/cache/pacman/pkg/
buildah run ${CONTAINER_NAME} rm -rf /home/builder/.cache/
buildah commit ${CONTAINER_NAME} arch_sandbox_deepinwine_tim:latest
buildah rm ${CONTAINER_NAME}
