CONTAINER_NAME=container_build_sandbox_base
buildah from --name ${CONTAINER_NAME} archlinux:latest 
buildah run ${CONTAINER_NAME} bash -c "echo 'Server = https://mirrors.bfsu.edu.cn/archlinux/\$repo/os/\$arch' > /etc/pacman.d/mirrorlist"
buildah run ${CONTAINER_NAME} bash -c "echo '[multilib]' >> /etc/pacman.conf"
buildah run ${CONTAINER_NAME} bash -c "echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf"
buildah run ${CONTAINER_NAME} bash -c "echo '[archlinuxcn]' >> /etc/pacman.conf"
buildah run ${CONTAINER_NAME} bash -c "echo 'Server = https://mirrors.bfsu.edu.cn/archlinuxcn/\$arch' >> /etc/pacman.conf"
buildah run  ${CONTAINER_NAME} pacman-key --init
buildah run  ${CONTAINER_NAME} pacman --noconfirm -Syu
buildah run  ${CONTAINER_NAME} pacman --noconfirm -S acl adobe-source-code-pro-fonts adwaita-icon-theme alsa-lib alsa-topology-conf alsa-ucm-conf aom archlinux-keyring argon2 at-spi2-atk at-spi2-core atk attr audit avahi base bash brotli bzip2 ca-certificates ca-certificates-mozilla ca-certificates-utils cairo cantarell-fonts celt coreutils cryptsetup curl dav1d db dbus dconf desktop-file-utils device-mapper e2fsprogs expat ffmpeg file filesystem findutils flac fontconfig freetype2 fribidi gawk gcc-libs gdbm gdk-pixbuf2 gettext giflib glib-networking glib2 glibc gmp gnupg gnutls gpgme graphite grep gsettings-desktop-schemas gsm gtk-update-icon-cache gtk3 gzip harfbuzz hicolor-icon-theme hidapi hwids iana-etc icu iproute2 iptables iputils iso-codes jack2 json-c json-glib kbd keyutils kmod krb5 l-smash lame lcms2 less libarchive libass libassuan libasyncns libavc1394 libbluray libcanberra libcap libcap-ng libcloudproviders libcolord libcroco libcups libdaemon libdatrie libdrm libedit libelf libepoxy libffi libgcrypt libglvnd libgpg-error libibus libice libidn2 libiec61883 libjpeg-turbo libksba libldap libmfx libmnl libmodplug libnetfilter_conntrack libnfnetlink libnftnl libnghttp2 libnl libogg libomxil-bellagio libp11-kit libpcap libpciaccess libpng libproxy libpsl libpulse libraw1394 librsvg libsamplerate libsasl libseccomp libsecret libsm libsndfile libsoup libsoxr libssh libssh2 libtasn1 libthai libtheora libtiff libtirpc libtool libunistring libunwind libusb libva libvdpau libvorbis libvpx libwebp libx11 libxau libxcb libxcomposite libxcrypt libxcursor libxdamage libxdmcp libxext libxfixes libxft libxi libxinerama libxkbcommon libxml2 libxrandr libxrender libxshmfence libxt libxtst libxv libxxf86vm licenses linux-api-headers llvm-libs lm_sensors lz4 lzo mesa mpfr ncurses nettle npth opencore-amr openjpeg2 openssl opus p11-kit pacman pacman-mirrorlist pam pambase pango pciutils pcre pcre2 pinentry pixman popt procps-ng psmisc rav1e readline rest sdl2 sed shadow shared-mime-info sound-theme-freedesktop speex speexdsp sqlite srt svt-av1 sysfsutils systemd systemd-libs systemd-sysvcompat tar tdb tzdata util-linux util-linux-libs v4l-utils vid.stab vmaf vulkan-icd-loader wayland wayland-protocols x264 x265 xcb-proto xkeyboard-config xorgproto xvidcore xz zimg zita-alsa-pcmi zita-resampler zlib zstd 
buildah run  ${CONTAINER_NAME} rm -rf /var/cache/pacman/pkg/
buildah commit ${CONTAINER_NAME} arch_sandbox_base:latest
buildah rm ${CONTAINER_NAME}
