#!/bin/bash
xhost local:
podman run \
    -it --rm \
    -v /tmp/.X11-unix:/tmp/.X11-unix:Z \
    -v ~/.Xauthority:/root/.Xauthority:Z \
    -v /dev/dri:/dev/dri:Z \
    --device /dev/video0 \
    --device /dev/snd \
    -e DISPLAY \
    -e http_proxy=http://10.0.2.2:8188 \
    -e https_proxy=http://10.0.2.2:8188 \
    --net slirp4netns:allow_host_loopback=true \
    -e XMODIFIERS=@im=fcitx \
    -e QT_IM_MODULE=fcitx \
    -e GTK_IM_MODULE=fcitx \
    -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native:Z \
    -e PULSE_SERVER=${XDG_RUNTIME_DIR}/pulse/native \
    -v ${XDG_RUNTIME_DIR}/bus:${XDG_RUNTIME_DIR}/bus:Z \
    -e DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus" \
    arch_sandbox_firefox \
    firefox
